### ISSUE TITLE
npm yaml2json does not work

### ISSUE THREAD

**Issue by tekknolagi** [keeferrourke/pandoc-cookbook#1]
After installing it, I try and run `make` and get the following error:

```
laurel% make      
[ERROR] couldn't read from '-i2':
ENOENT: no such file or directory, open '-i2'
pandoc: out/build.json: openBinaryFile: does not exist (No such file or directory)
```

This looks like the package does not support `-i` option maybe?

```
laurel% yaml2json -i2
[ERROR] couldn't read from '-i2':
ENOENT: no such file or directory, open '-i2'
laurel% 
```

**Comment by keeferrourke** [comment]
Ah figures that I'd muck something up in the documentation. The npm package is actually called `yamljs`, which provides binaries `yaml2json` and `json2yaml`. Sorry for the confusion!

**Comment by keeferrourke** [comment]
README has been updated! thanks for pointing this out :)
